### ISSUE TITLE
App is gone from Google Play Store

### ISSUE THREAD

**Issue by etremel** [passwordmaker/android-passwordmaker#39]
I just upgraded to a new Android phone, and I am now unable to download the PasswordMaker Pro app from the Google Play Store. When I search for the app, it does not appear in the search results, and if I go to [the Android PasswordMaker website](http://android.passwordmaker.org/) and click the "download" link at the top, it takes me to a page that says "We're sorry, the requested URL was not found on this server." What happened to it? How can I reinstall the app on my new phone?

**Comment by specialforest** [comment]
Indeed, why was it removed? etremel@ last time I had to build the app myself :(

**Comment by tasermonkey** [comment]
> Google Play will be required to target Android Oreo (API level 26) or higher. After this date, the Play Console will prevent you from submitting new APKs with a targetSdkVersion less than 26.

**Comment by jdstapleton** [comment]
wow.  It claims I have to target API 26.  Which is 6% of the share of the devices.

<img width="1108" alt="screen shot 2018-12-07 at 20 54 07" src="https://user-images.githubusercontent.com/5853065/49680449-6e5b0d00-fa62-11e8-94fb-420503385ed1.png">

**Comment by tasermonkey** [comment]
https://play.google.com/store/apps/details?id=org.passwordmaker.android its back on the store.
