### ISSUE TITLE
Unable to add new profiles manually

### ISSUE THREAD

**Issue by oranges13** [passwordmaker/android-passwordmaker#44]
The interface to view profiles does not provide a way to add new profiles in Android 8.1

Pixel XL - stock Android 8.1

https://i.imgur.com/65yQmSj.png

**Comment by specialforest** [comment]
Yep, I hit the same issue.

**Comment by tasermonkey** [comment]
Release: 2.0.12 seconds ago: Full rollout.

**Comment by oranges13** [comment]
Hi @tasermonkey Thank you for fixing this issue.

Unfortunately, now you can begin to create new profiles, but you cannot save them as there is no "save" button at the bottom, and there's no toolbar at the top to confirm. If you hit the "back" key the new profile is not saved.

http://i.imgur.com/AF8USWG.jpg

**Comment by tasermonkey** [comment]
I unfortunately know nothing about android development (they changed a ton since I really last touched it).  Maybe @specialforest can help with that.
